steps:
- id: 'Install node_modules'
  name: 'gcr.io/cloud-builders/yarn'
  dir: 'frontend'
  args: [ 'install', '--production', '--silent' ]

# - id: 'Lint'
#   name: 'gcr.io/cloud-builders/npm'
#   args: [ 'run', 'lint' ]

# - id: 'Unit tests'
#   name: 'gcr.io/cloud-builders/npm'
#   args: [ 'test' ]
#   env:
#   - 'CI=true'

- id: 'Build'
  name: 'gcr.io/cloud-builders/npm'
  dir: 'frontend'
  args: [ 'run', 'build' ]

- id: 'Deploy'
  name: 'gcr.io/$PROJECT_ID/firebase'
  dir: 'frontend'
  args: [ 'deploy', '-P', 'gcb-serverless-demo-staging', '--non-interactive' ]
  secretEnv: ['FIREBASE_TOKEN']

secrets:
- kmsKeyName: 'projects/gcb-serverless-demo/locations/global/keyRings/cloudbuilder/cryptoKeys/firebase-token'
  secretEnv:
    FIREBASE_TOKEN: 'CiQAk/Tam2QoTwFvOjuJoEByF0lp7/OYJSnFM8zMDJllS7iICNMSVgAI+LIrLNgc+Xu0HgBLpbsxibWHMi/VjntcVAQW3eDPJxIHQDhrX73B2un8StevImglWR9HW9eguoKwG6Fn0kngTStlFLyALWo2JQiq+qd3xrN4Mtsp'
