steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
  dir: 'functions'
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['test']
#   dir: 'functions'
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'beta',
    'functions',
    'deploy',
    'helloGET',
    '--trigger-http',
    '--source=.',
    '--project=${PROJECT_ID}'
  ]
  dir: 'functions'