steps:
- id: 'Build image'
  name: gcr.io/cloud-builders/docker
  dir: 'backend'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-staging:${COMMIT_SHA}', '.']

- id: 'Push to registry'
  name: gcr.io/cloud-builders/docker
  dir: 'backend'
  args: ['push', 'gcr.io/$PROJECT_ID/backend-staging:${COMMIT_SHA}']

- id: 'Deploy to staging'
  name: 'gcr.io/cloud-builders/gcloud'
  dir: 'backend'
  args: [
    'app', 
    'deploy', 
    'staging.app.yaml',
    '--version=$COMMIT_SHA',
    '--image-url=gcr.io/$PROJECT_ID/backend-staging:${COMMIT_SHA}',
    '--quiet'
  ]

images: ['gcr.io/$PROJECT_ID/backend-staging:${COMMIT_SHA}']